[package]
name = "protocol"
version = "0.1.0"
authors = ["Kirill Fomichev <fanatid@ya.ru>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.5.4"
prost = "0.6.1"

[build-dependencies]
prost-build = "0.6.1"
